trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: './Basket/src/BasketApi/BasketApi/BasketApi.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: './Basket/tests/BasketApi.IntegrationTests/BasketApi.IntegrationTests.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Install dotnet-stryker'
  inputs:
    command: custom
    custom: tool
    arguments: install dotnet-stryker --tool-path $(Agent.BuildDirectory)/tools

- task: Powershell@2
  displayName: 'Run dotnet-stryker'
  inputs:
    workingDirectory: './Basket/tests/BasketApi.IntegrationTests'
    targetType: 'inline'
    pwsh: true
    script: $(Agent.BuildDirectory)/tools/dotnet-stryker

- task: PublishMutationReport@1
  displayName: 'Publish Mutation Test Report'
  inputs:
    reportPattern: '**/mutation-report.html'
    reportDisplayName: 'My_Report'