trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: './Order/src/OrderApi/OrderApi/OrderApi.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: './Order/tests/OrderApi.IntegrationTests/OrderApi.IntegrationTests.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Install dotnet-stryker'
  inputs:
    command: custom
    custom: tool
    arguments: install dotnet-stryker --tool-path $(Agent.BuildDirectory)/tools

- task: Powershell@2
  displayName: 'Run dotnet-stryker'
  inputs:
    workingDirectory: './Order/tests/OrderApi.IntegrationTests'
    targetType: 'inline'
    pwsh: true
    script: $(Agent.BuildDirectory)/tools/dotnet-stryker

- task: PublishMutationReport@1
  displayName: 'Publish Mutation Test Report'
  inputs:
    reportPattern: '**/mutation-report.html'
    reportDisplayName: 'My_Report'