trigger: none

pool:
  vmImage: ubuntu-22.04

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: './Order/src/OrderApi/OrderApi/OrderApi.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Tests
  env:
    AzureConfiguration: $(APPCONFIG)
  inputs:
    command: test
    projects: './Order/tests/OrderApi.IntegrationTests/OrderApi.IntegrationTests.csproj'
    publishTestResults: true
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage results'
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/*coverage.cobertura.xml'

- task: PowerShell@2
  displayName: Install dotnet stryker
  inputs:
    targetType: 'inline'
    script: dotnet tool install -g dotnet-stryker

- task: PowerShell@2
  displayName: Run dotnet stryker
  env:
    AzureConfiguration: $(APPCONFIG)
  inputs:
    targetType: 'inline'
    workingDirectory: './Order/tests/OrderApi.IntegrationTests'
    script: dotnet stryker
  
- task: PublishMutationReport@1
  displayName: 'Publish Mutation Test Report'
  inputs:
    reportPattern: '**/mutation-report.html'
    reportDisplayName: 'My_Report'
