version: '3.4'

services:
  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: Product/src/ProductApi
      dockerfile: Product.Api/Dockerfile

  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: Order/src/OrderApi
      dockerfile: Dockerfile

  identityapi:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: Identity/src/IdentityApi
      dockerfile: Dockerfile

  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: Basket/src/BasketApi
      dockerfile: Dockerfile

  reverseproxy:
    image: ${DOCKER_REGISTRY-}reverseproxy
    build:
      context: ReverseProxy/ReverseProxy
      dockerfile: Dockerfile

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: Client/Dockerfile
