// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using OrderApi.Models;
using System;
using System.Collections.Generic;

namespace OrderApi.Models.Configurations
{
    public partial class OrderConfiguration : IEntityTypeConfiguration<Order>
    {
        public void Configure(EntityTypeBuilder<Order> entity)
        {
            entity.Property(e => e.OrderId)
                .ValueGeneratedNever()
                .HasColumnName("OrderID");

            entity.Property(e => e.AddressId).HasColumnName("AddressID");

            entity.Property(e => e.CouponId).HasColumnName("CouponID");

            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");

            entity.Property(e => e.Notes).HasMaxLength(50);

            entity.Property(e => e.OrderDate).HasColumnType("datetime");

            entity.Property(e => e.PaymentMethodId).HasColumnName("PaymentMethodID");

            entity.Property(e => e.ShipMethodId).HasColumnName("ShipMethodID");

            entity.Property(e => e.TotalPrice).HasColumnType("decimal(13, 2)");

            entity.HasOne(d => d.Address)
                .WithMany(p => p.Order)
                .HasForeignKey(d => d.AddressId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_Address");

            entity.HasOne(d => d.Coupon)
                .WithMany(p => p.Order)
                .HasForeignKey(d => d.CouponId)
                .HasConstraintName("FK_Order_Coupon");

            entity.HasOne(d => d.Customer)
                .WithMany(p => p.Order)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_Customer");

            entity.HasOne(d => d.PaymentMethod)
                .WithMany(p => p.Order)
                .HasForeignKey(d => d.PaymentMethodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_PaymentMethod");

            entity.HasOne(d => d.ShipMethod)
                .WithMany(p => p.Order)
                .HasForeignKey(d => d.ShipMethodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_ShipMethod");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Order> entity);
    }
}
