// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using OrderApi.Models;
using System;
using System.Collections.Generic;

namespace OrderApi.Models.Configurations
{
    public partial class SpecOrderStatusConfiguration : IEntityTypeConfiguration<SpecOrderStatus>
    {
        public void Configure(EntityTypeBuilder<SpecOrderStatus> entity)
        {
            entity.Property(e => e.SpecOrderStatusId)
                .ValueGeneratedNever()
                .HasColumnName("SpecOrderStatusID");

            entity.Property(e => e.OrderId).HasColumnName("OrderID");

            entity.Property(e => e.StatusDate).HasColumnType("datetime");

            entity.Property(e => e.StatusId).HasColumnName("StatusID");

            entity.HasOne(d => d.Order)
                .WithMany(p => p.SpecOrderStatus)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_SpecOrderStatus_Order");

            entity.HasOne(d => d.Status)
                .WithMany(p => p.SpecOrderStatus)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK_SpecOrderStatus_Status");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SpecOrderStatus> entity);
    }
}
