// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using OrderApi.Models;
using System;
using System.Collections.Generic;

namespace OrderApi.Models.Configurations
{
    public partial class SpecCustomerAddressConfiguration : IEntityTypeConfiguration<SpecCustomerAddress>
    {
        public void Configure(EntityTypeBuilder<SpecCustomerAddress> entity)
        {
            entity.Property(e => e.SpecCustomerAddressId)
                .ValueGeneratedNever()
                .HasColumnName("SpecCustomerAddressID");

            entity.Property(e => e.AddressId).HasColumnName("AddressID");

            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");

            entity.HasOne(d => d.Address)
                .WithMany(p => p.SpecCustomerAddress)
                .HasForeignKey(d => d.AddressId)
                .HasConstraintName("FK_SpecCustomerAddress_Address");

            entity.HasOne(d => d.Customer)
                .WithMany(p => p.SpecCustomerAddress)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_SpecCustomerAddress_Customer");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SpecCustomerAddress> entity);
    }
}
