apiVersion : apps/v1
kind: Deployment
metadata:
  name: webshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webshop
  template:
    metadata:
      labels:
        app: webshop 
    spec:
      containers:
        - name: webapp
          image: containerregistry32.azurecr.io/webapp:latest
          ports:
          - containerPort: 80
          
        - name: reverseproxy
          image: containerregistry32.azurecr.io/reverseproxy:latest
          ports:
          - containerPort: 3211

        - name: basketapi
          image: containerregistry32.azurecr.io/basketapi:latest
          ports:
          - containerPort: 3180
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          - name: "ASPNETCORE_HTTP_PORTS"
            value: "3180"

        - name: identityapi
          image: containerregistry32.azurecr.io/identityapi:latest
          ports:
          - containerPort: 3170
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          - name: "ASPNETCORE_HTTP_PORTS"
            value: "3170"

        - name: orderapi
          image: containerregistry32.azurecr.io/orderapi:latest
          ports:
          - containerPort: 3160
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          - name: "ASPNETCORE_HTTP_PORTS"
            value: "3160"

        - name: productapi
          image: containerregistry32.azurecr.io/productapi:latest
          ports:
          - containerPort: 3150
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          - name: "ASPNETCORE_HTTP_PORTS"
            value: "3150"

        - name: redis
          image: redis:7.2
          ports:
          - containerPort: 6379
            
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite
          ports:
          - containerPort: 10000

        - name: cosmosdb
          image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
          env:
          - name: "AZURE_COSMOS_EMULATOR_PARTITION_COUNT"
            value: "31"
          - name: "AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE"
            value: "true"
          ports:
          - containerPort: 8081

        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
          - containerPort: 1433
          env:
          - name: "SA_PASSWORD"
            value: "Passw@rd"
          - name: "ACCEPT_EULA"
            value: "Y"