apiVersion: v1
kind: Service
metadata:
    name: webshop-service
spec:
    type: LoadBalancer
    ports: 
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    selector:
        app: webshop
