// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderApi.Models
{
    public partial class Coupon
    {
        public Coupon()
        {
            Order = new HashSet<Order>();
        }

        public int CouponId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int Amount { get; set; }

        public virtual ICollection<Order> Order { get; set; }
    }
}