// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderApi.Models
{
    public partial class Customer
    {
        public Customer()
        {
            Order = new HashSet<Order>();
            SpecCustomerAddress = new HashSet<SpecCustomerAddress>();
        }

        public int CustomerId { get; set; }
        public string Email { get; set; }

        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<SpecCustomerAddress> SpecCustomerAddress { get; set; }
    }
}