// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderApi.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderItem = new HashSet<OrderItem>();
            SpecOrderStatus = new HashSet<SpecOrderStatus>();
        }

        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public DateTime? OrderDate { get; set; }
        public int PaymentMethodId { get; set; }
        public int AddressId { get; set; }
        public int ShipMethodId { get; set; }
        public decimal TotalPrice { get; set; }
        public string? Notes { get; set; }
        public int? CouponId { get; set; }

        public virtual Address Address { get; set; }
        public virtual Coupon Coupon { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual ShipMethod ShipMethod { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        public virtual ICollection<SpecOrderStatus> SpecOrderStatus { get; set; }
    }
}