// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderApi.Models
{
    public partial class SpecOrderStatus
    {
        public int SpecOrderStatusId { get; set; }
        public int? OrderId { get; set; }
        public int? StatusId { get; set; }
        public DateTime? StatusDate { get; set; }

        public virtual Order Order { get; set; }
        public virtual Status Status { get; set; }
    }
}