name: tests

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./Basket/src/BasketApi/BasketApi/BasketApi.csproj
    - name: Build
      run: dotnet build ./Basket/src/BasketApi/BasketApi/BasketApi.csproj
    - name: Test
      run: dotnet test ./Basket/tests/BasketApi.IntegrationTests/BasketApi.IntegrationTests.csproj
